const VALID_TERRAIN_TYPES = [
    "blank",
    "desolate",
    "grasslands",
    "hills",
    "mountains",
    "wetlands",
    "forest",
    "desert",
    "jungle",
    "water",
    "volcano"
];

const TERRAIN_TYPES = {
    badlands: {
        name: "Badlands",
        image: 'badlands',
        color: '#D68C48',
        types: ["desolate","hills"],
        description: "Barren desolation characterized by rocky eroded landforms with an alien appearance.",
    },
    blank: {
        name: "Blank",
        image: 'blank',
        color: '#FFFFFF',
        types: ['blank'],
        description: "Undefined or unknown, there is no terrain here.",
    },
    dense_evergreen_forest: {
        name: "Dense Evergreen Forest",
        image: 'dense_evergreen_forest',
        color: '#1C7048',
        types: ['forest'],
        description: "Densely populated evergreen forest with closely packed trees.",
    },
    dense_forest: {
        name: "Dense Forest",
        image: 'dense_forest',
        color: '#1A6933',
        types: ['forest'],
        description: "Thick densely forested area with abundant vegetation.",
    },
    dense_jungle: {
        name: "Dense Jungle",
        image: 'dense_jungle',
        color: '#006400',
        types: ['forest'],
        description: "Impenetrable jungles filled with an incredible diversity of flora and fauna.",
    },
    dense_mixed_forest: {
        name: "Dense Mixed Forest",
        image: 'dense_mixed_forest',
        color: '#007000',
        types: ['forest'],
        description: "A dense forest of mixed conifers and deciduous trees.",
    },
    desert_cactus_forest: {
        name: "Desert Cactus Forest",
        image: 'desert_cactus_forest',
        color: '#C9B57C',
        types: ['forest','desert'],
        description: "Sparse deserts, broken periodically by swaths of foliage adorned with clusters of cacti.",
    },
    desert_dense_cactus_forest: {
        name: "Dense Desert Cactus Forest",
        image: 'desert_dense_cactus_forest',
        color: '#A0A258',
        types: ['forest','desert'],
        description: "Sandy deserts dominated by dense walls and clusters of cacti.",
    },
    desert_dunes: {
        name: "Desert Dunes",
        image: 'desert_dunes',
        color: '#E0C17A',
        types: ['desert','hills'],
        description: "Trackless deserts dominated by rolling dunes and shifting valleys.",
    },
    desert_mesa: {
        name: "Desert Mesa",
        image: "mesa",
        color: "#CAA968",
        types: ['desert','mountains'],
        description: "A stone and clay mountain, towering above the arid sands of the desert.",
    },
    desert_oasis: {
        name: "Desert Oasis",
        image: 'oasis',
        color: '#F0D080',
        types: ['desert','grassland'],
        description: "A fertile plot amid the arid wastes, sufficient to support a tiny ecosystem of plants, animals and even sentient habitation",
    },
    desert_sandy: {
        name: "Trackless Desert",
        image: 'desert_sandy',
        color: '#F9D78C',
        types: ['desert'],
        description: "Trackless desert sands, spanning to the horizon.",
    },
    fen: {
        name: "Fens",
        image: 'fen',
        color: '#1DC989',
        types: ['wetland','grassland'],
        description: "Low-lying wetlands overrun with grasses and shrubbery.",
    },
    foothills: {
        name: "Foothills",
        image: 'foothills',
        color: '#A34E21',
        types: ['hills','mountains'],
        description: "Rolling hills at the base of great mountains.",
    },
    forested_evergreen_hills: {
        name: "Forested Evergreen Hills",
        image: 'forested_evergreen_hills',
        color: '#007020',
        types: ['forest','hills'],
        description: "Hilly expanses dominated by evergreen forests.",
    },
    forested_evergreen_mountain: {
        name: "Forested Evergreen Mountain",
        image: 'forested_evergreen_mountain',
        color: '#004C00',
        types: ['forest','mountain'],
        description: "A single great mountain peak, encircled by evergreen conifer forests.",
    },
    forested_evergreen_mountains: {
        name: "Forested Evergreen Mountains",
        image: 'forested_evergreen_mountains',
        color: '#296D50',
        types: ['forest','mountain'],
        description: "A range of mountains, blanketed by swathes of evergreens.",
    },
    forested_hills: {
        name: "Forested Hills",
        image: 'forested_hills',
        color: '#004C00',
        types: ['forest','hills'],
        description: "Hilly expanses dominated by rigid forests.",
    },
    forested_mountain: {
        name: "Forested Mountain",
        image: 'forested_mountain',
        color: '#295B33',
        types: ['forest','mountain'],
        description: "A great mountain, encircled by hardy forests.",
    },
    forested_mountains: {
        name: "Forested Mountains",
        image: 'forested_mountains',
        color: '#556B2F',
        types: ['forest','mountain'],
        description: "A range of mountains, densely populated with mighty trees.",
    },
    grassy_hills: {
        name: "Grassy Hills",
        image: 'grassy_hills',
        color: '#8AA431',
        types: ['grassland','hills'],
        description: "Rolling hills covered in lush grasses.",
    },
    hills: {
        name: "Hills",
        image: 'hills',
        color: '#8B4513',
        types: ['hills'],
        description: "Rocky, clay-domianted hills, with sparse vegetation.",
    },
    jungle_hills: {
        name: "Jungle Hills",
        image: 'jungle_hills',
        color: '#007000',
        types: ['forest','hills','jungle'],
        description: "Lush jungles adorning rolling hills",
    },
    jungle_mountain: {
        name: "Jungle Mountain",
        image: 'jungle_mountain',
        color: '#005400',
        types: ['forest','mountains','jungle'],
        description: "A single verdant mountain peak, towering over dense jungles",
    },
    jungle_mountains: {
        name: "Jungle Mountains",
        image: 'jungle_mountains',
        color: '#329659',
        types: ['forest','mountain','jungle'],
        description: "A mountain range, cutting a great jutting path through dense jungles.",
    },
    light_evergreen_forest: {
        name: "Light Evergreen Forest",
        image: 'light_evergreen_forest',
        color: '#3B9849',
        types: ['forest'],
        description: "A lightly forested area primarily comprised of evergreen trees.",
    },
    light_forest: {
        name: "Light Forest",
        image: 'light_forest',
        color: '#006400',
        types: ['forest'],
        description: "A lightly covered forested terrain with scattered trees.",
    },
    light_jungle: {
        name: "Light Jungle",
        image: 'light_jungle',
        color: '#006400',
        types: ['forest','jungle'],
        description: "Jungle edges, where dense vegetation encircles secluded clearings and paths.",
    },
    light_mixed_forest: {
        name: "Light Mixed Forest",
        image: 'light_mixed_forest',
        color: '#007000',
        types: ['forest'],
        description: "Lightly forested terrain with ample paths and clearings.",
    },
    marsh: {
        name: "Marsh",
        image: 'marsh',
        color: '#1DC9A9',
        types: ['wetland'],
        description: "Wetlands of standing water, featuring predominantly aquatic vegetation and very little solid ground.",
    },
    mixed_forested_hills: {
        name: "Mixed Forested Hills",
        image: 'mixed_forested_hills',
        color: '#408E5E',
        types: ['forest','hills'],
        description: "Hilly terrain featuring a variety of deciduous and evergreen trees.",
    },
    mixed_forested_mountain: {
        name: "Mixed Forested Mountain",
        image: 'mixed_forested_mountain',
        color: '#004C00',
        types: ['forest','mountains'],
        description: "Diverse forests of deciduous and evergreen trees encirlce a towering mountain peak.",
    },
    mixed_forested_mountains: {
        name: "Mixed Forested Mountains",
        image: 'mixed_forested_mountains',
        color: '#005E3E',
        types: ['forest','mountains'],
        description: "A mountain range dappled with clusters of evergreen and deciduous trees.",
    },
    mountain: {
        name: "Mountain",
        image: 'mountain',
        color: '#808080',
        types: ['mountains'],
        description: "A single lonely mountain, stretching to the clouds.",
    },
    mountains: {
        name: "Mountain",
        image: 'mountains',
        color: '#6F7D7D',
        types: ['mountains'],
        description: "The peaks and ridges of a mountain range project into the heavens and cut a majestic skyline.",
    },
    grassland: {
        name: "Grassy Plains",
        image: 'grassland',
        color: '#228B22',
        types: ['grassland'],
        description: "Great grassy plains rolling off into the horizon.",
    },
    sparse_evergreen_forest: {
        name: "Sparse Evergreen Forest",
        image: 'sparse_evergreen_forest',
        color: '#006400',
        types: ['forest','grasslands'],
        description: "Scattered evergreen trees break the uniformity of the plains here.",
    },
    sparse_forest: {
        name: "Sparse Forest",
        image: 'sparse_forest',
        color: '#006400',
        types: ['forest','grasslands'],
        description: "Scattered trees dapple the grassly plain.",
    },
    sparse_jungle: {
        name: "Sparse Jungle",
        image: 'sparse_jungle',
        color: '#006400',
        types: ['forest','grasslands','jungle'],
        description: "Open areas, pocked with tangled masses of jungle vegetation.",
    },
    swamp: {
        name: "Swamp",
        image: 'swamp',
        color: '#2EBB57',
        types: ['forest','wetland'],
        description: "Waterlogged wetland of dense vegetation, with generous swathes of willow and mangrove trees.",
    },
    volcano_dormant: {
        name: "Dormant Volcano",
        image: 'volcano',
        color: '#8F8F8F',
        types: ['mountains','volcano'],
        description: "A previously active caldera, now but a stony bowl atop a once-terrifying titanic volcano."
    },
    water_salt: {
        name: "Salt Water",
        image: 'water_salt',
        color: '#4444FF',
        types: ['water'],
        description: "A large body of salty water, unsuitable for drinking."
    },
    water_fresh: {
        name: "Fresh Water",
        image: 'water_fresh',
        color: '#AAAAFF',
        types: ['water'],
        description: "A large body of fresh water."
    },
};
// Check if running in a browser environment
if (typeof window !== 'undefined') {
    // Browser environment, define terrainTypes as a global variable
    window.TERRAIN_TYPES = TERRAIN_TYPES;
    window.VALID_TERRAIN_TYPES = VALID_TERRAIN_TYPES;
} else {
    // Node.js environment, export terrainTypes using module.exports
    module.exports = TERRAIN_TYPES, VALID_TERRAIN_TYPES;
}
